services:
  kometa-ai:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - ./test_data/kometa-config:/app/kometa-config
      - ./test_data/state:/app/state
      - ./logs:/app/logs
    environment:
      # User/Group ID configuration
      - PUID=1000    # Set this to your host user ID
      - PGID=1000    # Set this to your host group ID
      - RADARR_URL=http://mock-radarr:7878
      - RADARR_API_KEY=dev_api_key
      - CLAUDE_API_KEY=dev_api_key
      - DEBUG_LOGGING=true
    command: ["--run-now", "--dry-run"]
  
  mock-radarr:
    image: mockserver/mockserver
    ports:
      - "7878:1080"
    volumes:
      - ./test_data/mock_radarr:/mockserver/mockserver_expectations
