name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Setup directory structure
      run: |
        # Run pre-build setup script
        chmod +x ./scripts/pre_build_setup.sh
        ./scripts/pre_build_setup.sh
        
    - name: Install package in development mode
      run: |
        pip install -e .
        
    - name: Ensure state module is properly importable 
      run: |
        # Execute the CI state module fix script
        python ci_fix_state_module.py
        
    - name: Create sample data for testing
      run: |
        mkdir -p state
        mkdir -p kometa-config
        cp config-examples/basic-collections.yml kometa-config/collections.yml
        
        # Create test data using script
        python ci_ensure_test_data.py
        """
        Synthetic test data for movies and collections.
        This module provides sample data for testing without requiring external APIs.
        """
        
        from typing import Dict, List, Any
        
        # Sample synthetic movies with metadata
        synthetic_movies = [
            {
                "id": 1001,
                "title": "The Adventure Quest",
                "year": 2020,
                "overview": "A group of friends embark on an epic adventure to find a hidden treasure.",
                "genres": ["Adventure", "Action", "Fantasy"],
                "tagline": "The greatest adventure awaits",
                "runtime": 124,
                "rating": 7.8,
                "director": "Jane Smith",
                "actors": ["John Doe", "Sarah Johnson", "Mike Williams"],
                "studio": "Adventure Studios"
            },
            {
                "id": 1002,
                "title": "Mystery in the Dark",
                "year": 2018,
                "overview": "A detective investigates a series of mysterious disappearances in a small town.",
                "genres": ["Mystery", "Thriller", "Crime"],
                "tagline": "The truth lies in the shadows",
                "runtime": 112,
                "rating": 8.2,
                "director": "Robert Brown",
                "actors": ["Emily Clark", "David Wilson", "Linda Martin"],
                "studio": "Enigma Pictures"
            },
            {
                "id": 1003,
                "title": "Laugh Out Loud",
                "year": 2021,
                "overview": "A stand-up comedian tries to make it big while dealing with personal challenges.",
                "genres": ["Comedy", "Drama"],
                "tagline": "Sometimes life is the best punchline",
                "runtime": 98,
                "rating": 7.5,
                "director": "Michael Johnson",
                "actors": ["Lisa Adams", "Tom Clark", "Kevin White"],
                "studio": "Funny Films"
            },
            {
                "id": 1004,
                "title": "Space Explorers",
                "year": 2019,
                "overview": "A crew of astronauts discovers a new threat while exploring distant planets.",
                "genres": ["Sci-Fi", "Action", "Thriller"],
                "tagline": "The final frontier becomes the final battleground",
                "runtime": 135,
                "rating": 8.0,
                "director": "Steven Reynolds",
                "actors": ["Mark Stevens", "Julia Reed", "Ryan Thompson"],
                "studio": "Stellar Productions"
            },
            {
                "id": 1005,
                "title": "Historical Heroes",
                "year": 2017,
                "overview": "Based on true events, a group of unsung heroes changes the course of history.",
                "genres": ["Drama", "History", "War"],
                "tagline": "Courage knows no boundaries",
                "runtime": 142,
                "rating": 8.5,
                "director": "William Davis",
                "actors": ["James Wilson", "Patricia Moore", "Daniel Taylor"],
                "studio": "Legacy Films"
            }
        ]
        
        # Sample collection definitions
        synthetic_collections = [
            {
                "name": "Adventure Films",
                "description": "Movies focused on exciting journeys, quests, and exploration.",
                "criteria": "Movies with adventure themes, often featuring quests, journeys, or exploration into unknown territories. These films typically have action elements and exciting scenarios.",
                "tag": "adventure-films",
                "enabled": True
            },
            {
                "name": "Mystery Thrillers",
                "description": "Suspenseful movies with mystery elements.",
                "criteria": "Films that combine mystery and thriller elements, featuring investigations, suspense, and plot twists. Often includes detective stories or crime investigations.",
                "tag": "mystery-thrillers",
                "enabled": True
            },
            {
                "name": "Comedy Collection",
                "description": "Funny movies to lighten the mood.",
                "criteria": "Movies intended to make the audience laugh through humor, amusing situations, and comedy. Includes various comedy subgenres like romantic comedies, slapstick, or dark comedy.",
                "tag": "comedy-collection",
                "enabled": True
            },
            {
                "name": "Sci-Fi Adventures",
                "description": "Science fiction movies with adventure elements.",
                "criteria": "Movies that combine science fiction concepts with adventure storylines. Often features space exploration, futuristic technology, or alien encounters in an action-packed setting.",
                "tag": "scifi-adventures",
                "enabled": True
            },
            {
                "name": "Historical Dramas",
                "description": "Dramatic films set in historical periods.",
                "criteria": "Films based on or inspired by historical events and time periods. Often focuses on significant historical figures or events with dramatic storytelling.",
                "tag": "historical-dramas",
                "enabled": True
            }
        ]
        EOL
        
        # Create JSON files for testing
        cat > test_data/synthetic_movies.json << 'EOL'
        [
          {
            "id": 1001,
            "title": "The Adventure Quest",
            "year": 2020,
            "overview": "A group of friends embark on an epic adventure to find a hidden treasure.",
            "genres": ["Adventure", "Action", "Fantasy"],
            "tagline": "The greatest adventure awaits",
            "runtime": 124,
            "rating": 7.8,
            "director": "Jane Smith",
            "actors": ["John Doe", "Sarah Johnson", "Mike Williams"],
            "studio": "Adventure Studios"
          },
          {
            "id": 1002,
            "title": "Mystery in the Dark",
            "year": 2018,
            "overview": "A detective investigates a series of mysterious disappearances in a small town.",
            "genres": ["Mystery", "Thriller", "Crime"],
            "tagline": "The truth lies in the shadows",
            "runtime": 112,
            "rating": 8.2,
            "director": "Robert Brown",
            "actors": ["Emily Clark", "David Wilson", "Linda Martin"],
            "studio": "Enigma Pictures"
          },
          {
            "id": 1003,
            "title": "Laugh Out Loud",
            "year": 2021,
            "overview": "A stand-up comedian tries to make it big while dealing with personal challenges.",
            "genres": ["Comedy", "Drama"],
            "tagline": "Sometimes life is the best punchline",
            "runtime": 98,
            "rating": 7.5,
            "director": "Michael Johnson",
            "actors": ["Lisa Adams", "Tom Clark", "Kevin White"],
            "studio": "Funny Films"
          },
          {
            "id": 1004,
            "title": "Space Explorers",
            "year": 2019,
            "overview": "A crew of astronauts discovers a new threat while exploring distant planets.",
            "genres": ["Sci-Fi", "Action", "Thriller"],
            "tagline": "The final frontier becomes the final battleground",
            "runtime": 135,
            "rating": 8.0,
            "director": "Steven Reynolds",
            "actors": ["Mark Stevens", "Julia Reed", "Ryan Thompson"],
            "studio": "Stellar Productions"
          },
          {
            "id": 1005,
            "title": "Historical Heroes",
            "year": 2017,
            "overview": "Based on true events, a group of unsung heroes changes the course of history.",
            "genres": ["Drama", "History", "War"],
            "tagline": "Courage knows no boundaries",
            "runtime": 142,
            "rating": 8.5,
            "director": "William Davis",
            "actors": ["James Wilson", "Patricia Moore", "Daniel Taylor"],
            "studio": "Legacy Films"
          }
        ]
        EOL
        
        cat > test_data/synthetic_collections.json << 'EOL'
        [
          {
            "name": "Adventure Films",
            "description": "Movies focused on exciting journeys, quests, and exploration.",
            "criteria": "Movies with adventure themes, often featuring quests, journeys, or exploration into unknown territories. These films typically have action elements and exciting scenarios.",
            "tag": "adventure-films",
            "enabled": true
          },
          {
            "name": "Mystery Thrillers",
            "description": "Suspenseful movies with mystery elements.",
            "criteria": "Films that combine mystery and thriller elements, featuring investigations, suspense, and plot twists. Often includes detective stories or crime investigations.",
            "tag": "mystery-thrillers",
            "enabled": true
          },
          {
            "name": "Comedy Collection",
            "description": "Funny movies to lighten the mood.",
            "criteria": "Movies intended to make the audience laugh through humor, amusing situations, and comedy. Includes various comedy subgenres like romantic comedies, slapstick, or dark comedy.",
            "tag": "comedy-collection",
            "enabled": true
          },
          {
            "name": "Sci-Fi Adventures",
            "description": "Science fiction movies with adventure elements.",
            "criteria": "Movies that combine science fiction concepts with adventure storylines. Often features space exploration, futuristic technology, or alien encounters in an action-packed setting.",
            "tag": "scifi-adventures",
            "enabled": true
          },
          {
            "name": "Historical Dramas",
            "description": "Dramatic films set in historical periods.",
            "criteria": "Films based on or inspired by historical events and time periods. Often focuses on significant historical figures or events with dramatic storytelling.",
            "tag": "historical-dramas",
            "enabled": true
          }
        ]
        EOL
        
        # List the files to verify
        find test_data -type f | sort
        
    - name: Run tests
      run: |
        python scripts/run_ci_tests.sh --install
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
        
    - name: Type check with mypy
      run: |
        pip install mypy
        mypy kometa_ai
        
    - name: Test imports diagnostics
      run: |
        python test_imports.py
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-py${{ matrix.python-version }}
        path: |
          import_test_results.json
          import_test_results.log
          state_module_fix.log